name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main  # You can replace 'main' with your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js (specify the Node.js version)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use the Node.js version compatible with Angular

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci

    # Step 4: Build the Angular app
    - name: Build the app
      run: npm run build -- --base-href "https://rishi-singh26.github.io/stegno/"

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # The branch to deploy to
        folder: dist/browser/  # Path to the folder containing the build output
